version: "3.9"
services:
  app:
    image: node:18.13-alpine3.17
    working_dir: /app
    command: sh -c "yarn install --network-timeout=100000 && yarn dev -o"
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:1010:3000
      - 127.0.0.1:24678:24678
